project: 
  type: website
  output-dir: "." 

website:
  title: "Avery Fonda"
  navbar:
    # background: "#282424"
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Avery Fonda, 2024"

format:
  html:
    theme: 
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

